"""
app.paths
=========
Absolute filesystem paths for the project. Derived from this file's location
so the application can be launched from any working directory.

The repository root is the parent of the ``app`` package. From there the
project's input/output directories are resolved:

* ``ontology/`` — the Turtle ontology suite (``pc.ttl``, ``ind.ttl``,
  ``im.ttl``, ``amtmeta.ttl``, ``exhibitor_view.ttl``, ``visitor_view.ttl``,
  ``ind_view.ttl``).
* ``shapes/``   — SHACL shapes used by :mod:`app.validation` and the
  ``tests/test_shacl_shapes.py`` suite.
* ``templates/`` and ``static/`` — served by the Flask app (``static/`` is
  optional and only wired in when it exists).
* ``dist/``     — checked-in CSV exports regenerated by ``make dist``.

Environment-variable overrides
------------------------------
Each input/output directory accepts an environment-variable override. The
lookup order is:

1. an explicit override passed by the caller (e.g.
   :func:`app.routes.create_app` accepts ``ontology_dir=...``),
2. the matching environment variable (``AMT_ONTOLOGY_DIR``,
   ``AMT_SHAPES_DIR``, ``AMT_TEMPLATE_DIR``, ``AMT_STATIC_DIR``,
   ``AMT_DIST_DIR``),
3. the default location under ``REPO_ROOT``.

This is useful when the same wheel is deployed against different ontology
snapshots (staging vs production) without rebuilding.
"""

from __future__ import annotations

import os
from pathlib import Path

# ---------------------------------------------------------------------------
# Repository layout
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent


def _resolve(env_var: str, default: Path) -> Path:
    """Return *default*, or the resolved value of *env_var* when set.

    Empty / unset env values fall through to *default* so that
    ``AMT_ONTOLOGY_DIR=`` (empty) behaves the same as ``unset``.
    """
    override = os.environ.get(env_var, "").strip()
    return Path(override).expanduser().resolve() if override else default


ONTOLOGY_DIR = _resolve("AMT_ONTOLOGY_DIR", REPO_ROOT / "ontology")
SHAPES_DIR = _resolve("AMT_SHAPES_DIR", REPO_ROOT / "shapes")
TEMPLATE_DIR = _resolve("AMT_TEMPLATE_DIR", REPO_ROOT / "templates")
STATIC_DIR = _resolve("AMT_STATIC_DIR", REPO_ROOT / "static")
DIST_DIR = _resolve("AMT_DIST_DIR", REPO_ROOT / "dist")

# Canonical (and only) ontology serialization.
ONTOLOGY_EXT = "ttl"


def ontology_path(name: str) -> Path:
    """Return the absolute path to ``ontology/<name>.ttl``.

    ``name`` is the bare stem (e.g. ``"pc"``, ``"exhibitor_view"``). Honours
    the ``AMT_ONTOLOGY_DIR`` override set at module import time.
    """
    return ONTOLOGY_DIR / f"{name}.{ONTOLOGY_EXT}"
